#ifndef webgraphclibrs_h
#define webgraphclibrs_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

void dims(const uint8_t *str, size_t len, size_t *nodes, uint64_t *arcs);

void neighborhood(const uint8_t *str, size_t len, size_t node_id, size_t *neighborhood, size_t *n);

#endif  /* webgraphclibrs_h */
